import * as Joi from 'joi';

export const configurationValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'staging', 'production').default('development'),
  PORT: Joi.number().port().default(3000),
  API_PREFIX: Joi.string().default('api/v1'),
  POSTGRES_HOST: Joi.string().required(),
  POSTGRES_PORT: Joi.number().port().required(),
  POSTGRES_USER: Joi.string().required(),
  POSTGRES_PASSWORD: Joi.string().required(),
  POSTGRES_DATABASE: Joi.string().required(),
  POSTGRES_MAX_POOL: Joi.number().integer().min(1).default(20),
  POSTGRES_SSL: Joi.boolean().default(false),
  REDIS_HOST: Joi.string().required(),
  REDIS_PORT: Joi.number().port().required(),
  REDIS_USERNAME: Joi.string().allow('').optional(),
  REDIS_PASSWORD: Joi.string().allow('').optional(),
  KAFKA_CLIENT_ID: Joi.string().required(),
  KAFKA_BROKERS: Joi.string().required(),
  KAFKA_GROUP_ID: Joi.string().required(),
  KAFKA_SSL: Joi.boolean().default(false),
  KAFKA_SASL_MECHANISM: Joi.string().allow('').optional(),
  KAFKA_SASL_USERNAME: Joi.string().allow('').optional(),
  KAFKA_SASL_PASSWORD: Joi.string().allow('').optional(),
  JWT_PUBLIC_KEY: Joi.string().required(),
  JWT_PRIVATE_KEY: Joi.string().required(),
  HTTP_PROVIDER_TIMEOUT_MS: Joi.number().integer().min(1000).default(10000),
  OUTBOX_BATCH_SIZE: Joi.number().integer().min(1).max(1000).default(100),
  PROMETHEUS_DEFAULT_METRICS: Joi.boolean().default(true),
  SMPP_ENQUIRE_LINK_SECONDS: Joi.number().integer().min(5).default(30),
  SMPP_DEFAULT_WINDOW_SIZE: Joi.number().integer().min(1).default(16),
});
