apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-platform-api
spec:
  replicas: 4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-platform-worker-dispatch
spec:
  replicas: 6
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-platform-worker-dlr
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-platform-worker-outbox
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-platform-control-plane
spec:
  replicas: 3
