apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-platform-api
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-platform-worker-dispatch
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-platform-control-plane
spec:
  replicas: 2
